### ISSUE TITLE
mullvad-split-tunneling + wireguard with allowedips = 0.0.0.0/0

### ISSUE THREAD

**Issue by paradilldel90** [mullvad/win-split-tunnel#42]
Hello! I'm really stuck...
I trying to use mullvad-split-tunnel driver with wireguard (config uses AllowedIPs = 0.0.0.0/0, ::/0).
I configure driver with the application driverlogic for using split-firefox, so when i put local networks in allowedips it works like a charm - firefox traffic being splitted. But when it's just 0.0.0.0/0 - all packets from firefox just drop...

**Comment by dlon** [comment]
Hello!

Are you trying to use the driver without the Mullvad app? If so, we don't provide support for that use case.

You can take a look at the [app's firewall](https://github.com/mullvad/mullvadvpn-app/tree/main/windows/winfw), since this code makes assumptions about filters/sublayers that are set up by that app.

Please reopen this if I've misunderstood your question.
